name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Google Java Format
      run: |
        export JAVA_HOME="${RUNNER_TEMP}/adoptopenjdk-11-hotspot"
        curl -L https://github.com/google/google-java-format/releases/download/google-java-format-1.10/google-java-format-1.10-all-deps.jar -o google-java-format.jar

    - name: Check code formatting
      run: |
        java -jar google-java-format.jar --set-exit-if-changed --aosp --style google-java-format.xml $(find . -name '*.java')

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: umutogadiya/spring-boot-maven
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
